export const HOST_URL = 'http://192.168.16.101:8080/sgrepostaje/services';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const PERMISSION_REQUEST_LIST = 'PERMISSION_LIST_REQUEST';
export const PERMISSION_LIST_SUCCESS = 'PERMISSION_LIST_SUCCESS';
export const PERMISSION_LIST_ERROR = 'PERMISSION_LIST_ERROR';
